/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Malbeasy (https://sketchfab.com/Malbeasy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/male-base-mesh-t-poserigged-5d91d2f079814476b9d471e7a09a5c39
Title: Male Base Mesh (T- Pose)+(Rigged)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function HackerRoom(props) {
  const { nodes, materials }= useGLTF('/models/male_base_mesh_t-_poserigged.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.90}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          geometry={nodes.Object_85.geometry}
          material={materials.Material}
          skeleton={nodes.Object_85.skeleton}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/male_base_mesh_t-_poserigged.glb')
